apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "client.fullname" . }}
  labels:
    {{- include "client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "client.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      serviceAccountName: {{ include "client.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:  
            - name: NEXT_PUBLIC_BEERA_API_URL
              value: {{ .Values.client.NEXT_PUBLIC_BEERA_API_URL }}
            - name: NEXT_PUBLIC_BEERA_API_WS_URL
              value: {{ .Values.client.NEXT_PUBLIC_BEERA_API_WS_URL }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
